# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

font_family      Iosevka Term
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 18.0

cursor_trail_decay 0.1 0.4
cursor_trail 1
cursor_shape block

cursor_blink_interval 0

draw_minimal_borders yes
window_margin_width 5
window_padding_width 3

background_opacity 1

editor /usr/bin/micro

# Color theme
include colors.conf

# Font rendering
font_smooth_body 0
box_drawing_scale 0.001, 1, 1.5, 2
confirm_os_window_close 0

macos_option_as_alt left

map cmd+shift+enter new_window
map cmd+shift+right next_window
map cmd+shift+left  previous_window
map cmd+w no_op
map cmd+t no_op

# Tmux integration
map shift+enter send_text all \x1b[13;2u
map shift+backspace send_text all \x1b[127;2u

map cmd+1 send_text all \x1b1
map cmd+2 send_text all \x1b2
map cmd+3 send_text all \x1b3
map cmd+4 send_text all \x1b4
map cmd+5 send_text all \x1b5
map cmd+6 send_text all \x1b6
map cmd+7 send_text all \x1b7
map cmd+8 send_text all \x1b8
map cmd+9 send_text all \x1b9

# Command+T ile tmux'ta yeni window aç
map cmd+t send_text all \x1bT
map cmd+w send_text all \x1bw

map cmd+left send_text all \x1b[1;3D
map cmd+right send_text all \x1b[1;3C
map cmd+up send_text all \x1b[1;3A
map cmd+down send_text all \x1b[1;3B

map ctrl+tab send_text all \x1b[18~
map ctrl+shift+tab send_text all \x1b[19~

# Command+F ile zoom (tmux pane zoom veya nvim window zoom)
map cmd+f send_text all \x06

# map cmd+v send_text all \x1bv
# map cmd+h send_text all \x1bh

map cmd+t send_text all \x1bt
map cmd+shift+t send_text all \x1bT
