# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

 font_family      Iosevka Term
 bold_font        auto
 italic_font      auto
 bold_italic_font auto
 font_size 14.0

 cursor_trail_decay 0.1 0.4
 cursor_trail 1
 cursor_shape block 

cursor_blink_interval      0

 draw_minimal_borders yes
window_margin_width 5
window_padding_width 3

 active_border_color #434A59
 background_opacity         1


 editor /usr/bin/micro

include colors.conf
confirm_os_window_close 0
