preload =/home/enes/.dotfiles/wallpapers/samurai.jpg
wallpaper = DP-1,/home/enes/.dotfiles/wallpapers/samurai.jpg
 
#enable splash text rendering over the wallpaper
splash = true
 
#fully disable ipc
# ipc = off
