return {}
-- return {
--   'github/copilot.vim',
--   config = function()
--     vim.keymap.set('i', '<C-Space>', 'copilot#Trigger()', { expr = true, noremap = true })
--     vim.keymap.set('i', '<C-n>', 'copilot#Next()', { expr = true, noremap = true })
--     vim.keymap.set('i', '<C-p>', 'copilot#Prev()', { expr = true, noremap = true })
-- vim.keymap.set('i', '<C-l>', 'copilot#Accept()', { expr = true, noremap = true })
--
--     vim.g.copilot_no_tab_map = true
--   end,
-- }
